### ISSUE TITLE
Bilder in Posts anpassen

### ISSUE THREAD

**Issue by meistermeier** [JUG-Ostfalen/JUG-Ostfalen.github.io#1]
In diesem Schritt müssen nur Links und Image Tags angepasst werden. Beispiel:
`<a href="/assets/2014/12/TestingWithAStrangerAudience1.jpg"><img src="assets/TestingWithAStrangerAudience1-300x225.jpg" alt="TestingWithAStrangerAudience1" width="300" height="225" class="alignright size-medium wp-image-1385" /></a>`

- [x] Link zum richtigen Asset
- [x] Image source auf das Asset setzen (im ersten Schritt gleiches Asset laden)

**Comment by schauder** [comment]
Können wir den Punkt schliessen?

**Comment by meistermeier** [comment]
ich glaube ja
