### ISSUE TITLE
ICS Kalender

### ISSUE THREAD

**Issue by schauder** [JUG-Ostfalen/JUG-Ostfalen.github.io#10]
Alle zukünftigen Events, die von der jug ostfalen selbst kommen sollten im ics Format herunter ladbar sein.

**Comment by meistermeier** [comment]
Finde ich eine sehr gute Idee. Müssten wir wahrscheinlich irgendwie "pre-compilen". Viel Lust, da per Hand die Sachen im ics Format zu pflegen habe ich nicht ;)

**Comment by schauder** [comment]
Aber template sollte gehen: https://gist.github.com/woodworker/6725728

**Comment by meistermeier** [comment]
Ich sehe das richtig, wenn wir von einer Datei sprechen, oder? Nicht pro Event eine neue.

**Comment by schauder** [comment]
Eine Datei, in der alle zukünftigen Termine stehen, die von der JUG selbst kommen (in den events stehen auch Messen und dergleichen drin, die sollen nicht in die ics Datei)

**Comment by schauder** [comment]
fixed with commit 5d905c49191474f21e0fd68

**Comment by schauder** [comment]
Ich hätte übrigens gerne eine Datei pro Event, aber das scheint schwierig zu sein.
