### ISSUE TITLE
Sortierung der Assets

### ISSUE THREAD

**Issue by meistermeier** [JUG-Ostfalen/JUG-Ostfalen.github.io#2]
Ich persönlich fand die Sortierung der Assets in der Wordpressart (assets/<Jahr>/<Monat>) nicht so schlecht. Ein Ordner für alles ist evtl. too much.

**Comment by schauder** [comment]
Ok, ich habe da ja schon wieder Chaos verbreitet. 

Aktueller Stand ist: 
assets/wp/<year> enthält Bilder und ähnliches von Wordpress. finde ich gut
assets/ verschiedene Dinge
images/ verschiedene andere Dinge

Ich schlage folgende Struktur vor:
images/ entfernen
unter assets/
main/ resourcen die für die nackige Webseite notwendig sind: favicon, logo der jug, 
partners/ logos der Veranstalter (ckc, t-systems ...) sponsoren und ähnlichem
articles/<jahr> Dinge die nur für einzelne Artikel benötigt werden.

Meinungen?

**Comment by meistermeier** [comment]
Meiner Meinung nach passend.
