### ISSUE TITLE
weiterlesen-Link, wenn Eintrag länger

### ISSUE THREAD

**Issue by meistermeier** [JUG-Ostfalen/JUG-Ostfalen.github.io#21]
Wenn ein Eintrag länger ist, sollte ein Link am Ende der Zusammenfassung stehen. Das hat meiner Meinung nach vor allem den Vorteil, dass sofort ersichtlich ist, ob ein Eintrag weiteren Text hat oder nur aus dem ohnehin schon in der Zusammenfassung stehenden Absatz besteht.

**Comment by schauder** [comment]
yupp, finde ich gut.
