### ISSUE TITLE
Cookie Disclaimer einbauen

### ISSUE THREAD

**Issue by schauder** [JUG-Ostfalen/JUG-Ostfalen.github.io#28]
Dank der Vollpfeifen, die Gesetze machen, brauchen wir wohl einen Cookie Disclaimer ....

**Comment by meistermeier** [comment]
ja, wenn wir denn cookies nutzen würden. Also kein Stress aus meiner Sicht.

**Comment by schauder** [comment]
Ich habe mich von meinem Browser reinlegen lassen. Die Cookies, die ich da gesehen hab, waren wohl noch aus der Wordpress Zeit.
