### ISSUE TITLE
ICS so finetunen, dass es automatisch für Newsletter verarbeitet werden kann

### ISSUE THREAD

**Issue by schauder** [JUG-Ostfalen/JUG-Ostfalen.github.io#36]
Hallo,

auf Anregung der JUG Darmstadt habe ich ein kleines
Skript geschrieben, dass die Termine aus dem Terminkalender
(URL zu einer ICS-Datei)
der JUG holt und sie fuer den Newsletter aufbereitet.
Das Ergebnis steht dann hier:
http://java.de/ijugtermine.txt

Es werden immer die Termine des aktuellen Monats und
des naechsten Monats angezeigt.

Man muss sich an zwei Vorgaben halten:
- Der/Die Referenten stehen in Klammern am Schluss
  des Summary
- Der Ort ist der letzte zusammenhaengende String
  in Location

Bisher werden nur die ICS-Dateien von Darmstadt
und Goettingen genutzt und von mir per Hand zu
Redaktionsschluss des iJUG Newsletter ins Wiki
kopiert.

Weitere Kalender werden nur nach Zuruf in die Liste
aufgenommen. Wer sich nicht an die Vorgaben haelt,
fliegt wieder aus der Liste raus.

Die gleiche ICS-Datei wird fure die Anzeige auf java.de
genutzt:
http://www.java.de/roller/blog/page/user_group_treffen
Auch wenn ihr eure Termine lieber selbst ins Wiki
eingebt, waere es toll, wenn ihr auf der Seite, den
ics-LINK und den Link zu euere Webseite ueberpruefen
wuerdet.

-> Wenn Ferting Stefan Kospal Bescheid geben

**Comment by meistermeier** [comment]
Wir sind nun im Newsletter mit unseren Terminen verzeichnet. Ich sehe das somit als erledigt an :)
