### ISSUE TITLE
URLs retten

### ISSUE THREAD

**Issue by schauder** [JUG-Ostfalen/JUG-Ostfalen.github.io#4]
Es wäre schön wenn wir die alten URLs wieder herstellen können, damit evtl. vorhandene Links weiterhin funktionieren.

Allerdings nutzt Jug-ostfalen einfache post ids in den urls, die nicht in den exportierten Daten enthalten zu sein scheinen. Ich bin mir daher nicht sicher ob wir das automatisiert bereinigt bekommen.

**Comment by schauder** [comment]
Mir fällt hier nichts besseres ein, als auf die URLs zu pfeifen und redirects zu bauen.

Hiermit sollte das gehen: https://help.github.com/articles/redirects-on-github-pages/

Das würde ich dann für die wesentlichen Seiten, d.h. diejenigen, die in wp pages waren tun. 
Für alle anderen Seiten, würde ich 
a) eine ordentliche http 404 Seite bauen 
b) das ganze mit google webmaster beobachten, um die Seiten die tatsächlich Traffic produzieren ordentlich verlinkt werden.

**Comment by meistermeier** [comment]
Kann das nicht langsam zu?
