### ISSUE TITLE
HackTalk Termine template

### ISSUE THREAD

**Issue by meistermeier** [JUG-Ostfalen/JUG-Ostfalen.github.io#40]
Mir ist aufgefallen, dass der Content in den HackTalk-Terminen über die Zeit immer gleich bleibt. Meine Idee wäre es, dass wir ein template bauen, dass wir über include reinziehen können und dann nur noch Metadaten, wie Termin, Ort und der Xing Link eingefügt werden müssen.
Es lief ja bei den letzten Artikeln schon recht gut, aber das würde die Fehleranfälligkeit schon noch drastisch verringern ;)

Ich glaube, das ist mit GitHub "Hosting" nicht möglich, aber vielleicht kann man sogar die Artikel generieren lassen und muss noch nicht einmal die Stubs anlegen. Dann hätte man nur noch ein Configobjekt/-Array mit allen Daten.

**Comment by schauder** [comment]
Ich denke dass sollte sich über ein eigenes Layout recht einfach abbilden lassen und dann auch Github pages kompatibel sein.

**Comment by meistermeier** [comment]
Aber das führt trotzdem dazu, dass wir weiterhin Artikel-Dateien mit den Metadaten erstellen müssen, wenn ich das richtig sehe. Meine Vorstellung basiert auf der Annahme, dass wir einfach eine Datei mit allen Terminen (quasi so collection like) haben. Das scheint aber nicht zu gehen.
Falls Dir dazu noch eine Idee kommt, gerne her damit, ansonsten würde ich https://github.com/JUG-Ostfalen/JUG-Ostfalen.github.io/pull/41 nehmen.

**Comment by schauder** [comment]
Aus einem Dokument (oder sogar 0 Dokumenten) meherere Seiten zu bekommen ist schwierig, bis unmöglich, wenn ich das richtig sehe. vgl https://github.com/jekyll/jekyll/issues/3041

Ich finde ein Dokument nur mit Metadaten pro Event aber auch sehr in Ordnung..

**Comment by schauder** [comment]
@meistermeier Ist der Punkt mit dem neuen Layout erledigt?

**Comment by meistermeier** [comment]
Jupp, finde ich erstmal ok so.
