### ISSUE TITLE
Haftungsklausel ins Impressum

### ISSUE THREAD

**Issue by schauder** [JUG-Ostfalen/JUG-Ostfalen.github.io#42]
Wir sollten was ins Impressum reinschreiben, dass "unsere" Events vom iJUG veranstaltet werden.

**Comment by meistermeier** [comment]
würde dann gleich in Tateinheit im event template einen control block anlegen, der schaut, ob wir es sind und wenn ja, noch einmal den standardisierten Text unten anfügen.
