### ISSUE TITLE
Eventseite befüllen

### ISSUE THREAD

**Issue by schauder** [JUG-Ostfalen/JUG-Ostfalen.github.io#48]
@meistermeier Magst du mal deine Vortragsinfos vervollständigen: https://github.com/JUG-Ostfalen/JUG-Ostfalen.github.io/tree/talks-in-vorbereitung

**Comment by meistermeier** [comment]
Mache ich.

**Comment by meistermeier** [comment]
Sollte nun mit 0391e83 gelöst sein. Ich habe die Startzeit noch angepasst, da ich davon ausgehe, dass es sich in WOB um 18h handelt, richtig?

**Comment by schauder** [comment]
Richtig!
