### ISSUE TITLE
iJUG-Disclaimer wird auch für gemeinsame Events (.NET UG) angezeigt

### ISSUE THREAD

**Issue by omilke** [JUG-Ostfalen/JUG-Ostfalen.github.io#54]
Wenn wir gemeinsame Events beispielsweise mit der .NET User Group auf unserer Seite veröffentlichen, darf der Disclaimer vom iJUG (_Eine Veranstaltung des iJUG e.V., organisiert durch die JUG Ostfalen._) nicht angezeigt werden.

Beispiel: https://www.jug-ostfalen.de/event/2018/11/20/dsgvo-und-cloud-act.html

Wahrscheinlich sollte dieser Disclaimer nur dann angezeigt werden, wenn der Veranstalter entweder "JUG" oder "ijug" ist.

Related: #31

**Comment by meistermeier** [comment]
Ich habe nun erst einmal mich darauf beschränkt, nur unsere Veranstaltungen ("JUG") mit dem Disclaimer zu kennzeichnen. Ansonsten würde der Text auch nicht passen.
