### ISSUE TITLE
Neues Logo?

### ISSUE THREAD

**Issue by schauder** [JUG-Ostfalen/JUG-Ostfalen.github.io#6]
Ich habe mir von Uwe die Logo Dateien geben lassen. Die kommen wohl von dieser Seite: http://mindprod.com/jgloss/icon.html

Das Ganze liegt jetzt in einem eigenen Repository:https://github.com/JUG-Ostfalen/logo

Ich finde das Logo nicht so besonders prall ... andererseits ist es nun mal seit 5 Jahren das Logo der JUG. 

Brauchen / Wollen wir ein neuese Logo?

**Comment by bennetelli** [comment]
Wie wäre es mit einem Duke, der eine Löwenmaske auf hat und eine Wolfmaske in der Hand?

**Comment by bennetelli** [comment]
duke: https://duke.kenai.com/wave/Wave.png
der löwe: http://www.bambinogoodies.co.uk/wp-content/uploads/2012/09/lion-mask.jpg

einen löwen im comik-style so wie der obige Link. Was haltet ihr grundlegend davon?

**Comment by schauder** [comment]
+1

**Comment by bennetelli** [comment]
Gute Nachrichten :+1: mein Arbeitgeber hat Unterstützung angekündigt. Ich werde nächste Woche mit meinen Vorstellungen zu unserer Grafikerin gehen und sie darauf ansetzen.

**Comment by meistermeier** [comment]
:party: Super

**Comment by meistermeier** [comment]
Gibt es nun eigentlich schon etwas neues vom Logo? Bin gespannt.

**Comment by bennetelli** [comment]
Kam erst letzte Woche dazu, da ich das Bett hüten musste. Aus der eigens geplanten Grafikerin ist nun ein Grafiker geworden. Er liest sich gerade in die Thematik der Region Ostfalen rein und überlegt sich neben meinem Vorschlag noch weitere Ideen.

Habt ihr vielleicht noch irgendwelche Vorschläge ausser einem Wolf und einem Löwen, die die Region ausmachen bzw. die mit ins Logo könnten? Vielleicht kann man heute Abend ja nochmal zu einem Aufruf zur Ideensammlung aufrufen?

**Comment by meistermeier** [comment]
Ist hier eigentlich in der Zwischenzeit was passiert?

**Comment by bennetelli** [comment]
Würde mich auch inreressieren
Am 05.08.2015 10:07 schrieb Gerrit Meier <notifications@github.com>:Ist hier eigentlich in der Zwischenzeit was passiert?

**Comment by schauder** [comment]
Ja, das Logo designen geht vorran und ich werde vermutlich die jeweils aktuelle Version in die Seite einbauen.

**Comment by schauder** [comment]
Das Logo steht zur Verfügung.

Wir haben einen Duke ... wird schon als Partner Icon und favicon verwendet.

Ein großes Banner. Wir überlegen gerade wie wir das sinnvoller Weise verwenden.
