### ISSUE TITLE
Events vernünftig in Google präsentieren

### ISSUE THREAD

**Issue by schauder** [JUG-Ostfalen/JUG-Ostfalen.github.io#8]
Dies könnte für uns interessant sein: https://www.google.com/webmasters/tools/data-highlighter?hl=en&siteUrl=http://blog.schauderhaft.de/

**Comment by meistermeier** [comment]
kann man nur sehen, wenn die Seite einem selbst gehört. 
>You are signed in as meistermeier@gmail.com, and you can't view details for blog.schauderhaft.de. Verify to get access.

**Comment by schauder** [comment]
Hier ein Link, der unabhängig von einer Site ist. Es geht mir vor allem darum, dass events möglichst bei Google gleich als solche auftauchen.

**Comment by meistermeier** [comment]
Leider kein Link zu sehen.

**Comment by schauder** [comment]
https://support.google.com/webmasters/answer/2692911?hl=en

**Comment by msanecki** [comment]
Hallo zusamme,
ich kann micht mit diese Thema beschäftigen.

**Comment by schauder** [comment]
Super, danke dafür schon mal.

**Comment by schauder** [comment]
Markup ist drin und wird von Google laut Webmaster Tools auch erkannt. Also erledigt

**Comment by meistermeier** [comment]
Das scheint noch immer nicht zu klappen?! Einfach google suche nach JUG Ostfalen bringt als erstes die Website als Treffer, jedoch ohne irgendwelche weiteren Angaben, wie man es nun erwarten würde.

**Comment by schauder** [comment]
Jain,

Google erkennt die Events korrekt (zeigt aktuell 26 gefundene Events und 0 mit Fehlern an).

Bei einer Suche nach `ostfalen security` wird das Event auch mit Datum angezeigt:

![image](https://cloud.githubusercontent.com/assets/136683/14204116/3596000c-f802-11e5-96e9-510c72f44faf.png)

Wenn Google das nicht für so wichtig hält, können wir da nicht viel machen, oder?

**Comment by meistermeier** [comment]
Ahh..ich verstehe, was nun geht. Problem ist dann anscheinend der Datahighlighter für die Hauptseite, weil wir dort dieses JS-Zeug nicht reinbringen.
Das wäre meiner Meinung nach noch einen Versuch wert. Ich kann das gerne nochmal die Tage ausprobieren, aber du musst dann mit den Tools reinschauen. Gebe dann hier Feedback.

**Comment by schauder** [comment]
oh, stimmt. Ist nur auf den Einzeleventseiten, also auch nicht auf der "Alle Events"

**Comment by schauder** [comment]
Habe dich bei den Google Webmaster tools mit eingerichtet, müsstest jetzt selbst drauf können.

**Comment by meistermeier** [comment]
Hab das Javascript-Tag nebenbei nun mal auf die index-Seite losgelassen :smile: Der Checker gibt nur ein Warning pro Event aus. Nun mal abwarten, wann es in den Ergebnissen aufschlägt.

**Comment by meistermeier** [comment]
Noch einmal für Events ergänzt und einen Filter für nur JUG-Events eingebaut. Bis jetzt leider noch keine Ergebnis auf der Search Console von der gestrigen Änderung zu sehen. Werde noch einmal abwarten.

**Comment by schauder** [comment]
google hat meta data auf der Startseite gefunden, bei den Sucheergebnissen sehe ich keine signifikante Veränderung

**Comment by meistermeier** [comment]
Du meinst schon "keine signifikante" im Sinne von "keine", oder? ;)
Naja, ein Versuch war es wert und jetzt wo der structured data parser das auch so erkennt, werde ich mich noch einmal dransetzen und alles so nachziehen, wie oben beschrieben. Wenn dann mal der spider von google zuschlägt, ist alles top :smiley_cat:

**Comment by schauder** [comment]
Google findet die Daten und nutzt sie. 

Sieht nicht so beeindruckend aus, wie ich das erhofft hatte, aber das können wir wohl nicht ändern
